#!/bin/bash

# kill any remaining audio procs
ps aux | grep record | head -n3 |\
    awk '{ print $2 }' | xargs -L 1 sudo kill

# free up any exported GPIOs
sudo bash ./script/unexport.sh

# beginning running mewsician, w/o warnings, and pass in auth
sudo python -W ignore python/mewsicode.py $(cat chip.auth)
